#! /bin/sh


multihead_desktops='IV V VI'
bspc monitor eDP1 -d I II III 

dunst &
picom -b

HDMI1_status=$(xrandr -q | awk '/^HDMI1/{print $2}')
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
if [[ $HDMI1_status = 'connected' ]]; then
	xrandr --output eDP1 --auto --output HDMI1 --auto --right-of eDP1 
	bspc monitor HDMI1 -d $multihead_desktops
else
	xrandr --output eDP1 --auto  --output HDMI1 --off
	for desk in $multihead_desktops; do
		bspc desktop $desk --to-monitor 'eDP1'
		bspc desktop $desk --remove
	done
fi

# if sxhd is running, reload it
# pgrep -x sxhkd > /dev/null && pkill -USR1 -x sxhkd
# if it isn't, start it 
pgrep -x sxhkd > /dev/null || sxhkd &


bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


$HOME/.config/polybar/launch.sh



bgdice

# turn of DPMS
xset s off -dpms

# transparency
# picom -b

# automount devices
udiskie --no-notify &

# start DE own services
systemctl --user start check-battery.timer

# polkit agent for authentification
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &>/dev/null &

# Window rules
#######
# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
